name: Generate snake game

on:
  schedule:
    # Execute once every 12 hours (at minute 0 of hour 0 and 12)
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Step 1: Initialize the workspace
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Step 2: Generate the Snake Animation
      - name: Snake Animation
        uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Step 3: Deploy to the output branch
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
